### ISSUE TITLE
tableLoad documentation lowercase

### ISSUE THREAD

**Issue by jordan2lee** [bmeg/sifter#42]
Name in parameter table should be rendered to match what the user will use, in this case all should be lowercase first letter, screenshot of current capitalization (ex. Input to input)

To do this, this html [file](https://github.com/bmeg/sifter/blob/main/docs/docs/inputs/tableload/index.html) should be updated

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/40308471/209029554-eb5edcd5-3d8f-47a5-b3f7-305da8942aab.png">

**Comment by kellrott** [comment]
Addressed in 5f19e4efb2bfec5d79105b426fc00d43b6b56f27
